# Generated by Django 3.1.3 on 2020-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201117_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sub_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
