# Generated by Django 3.1.3 on 2020-12-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201117_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('title',), 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
    ]
