# Generated by Django 3.1.3 on 2020-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
