# Generated by Django 3.1.3 on 2020-11-16 17:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('order_by',), 'verbose_name': 'program', 'verbose_name_plural': 'programs'},
        ),
        migrations.AddField(
            model_name='program',
            name='order_by',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
