# Generated by Django 3.1.3 on 2020-11-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20201116_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='order_by',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
