# Generated by Django 3.1.3 on 2020-11-17 02:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20201116_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
