# Generated by Django 3.1.3 on 2020-12-04 11:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20201117_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='content_intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
