# Generated by Django 3.1.3 on 2020-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20201117_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
